### ISSUE TITLE
Incorrect naming in Object Workflows lesson

### ISSUE THREAD

**Issue by lindabeau70** [World-of-Workflows/WorkflowsUniversity#82]
Navigate to Workflow Development>Object Workflows - part 4. Execute and Test Workflow
https://world-of-workflows.github.io/WorkflowsUniversity/docs/object-workflows.html#4-execute-and-test-workflow

Where it says:
1. Navigate to Admin -> Data

It should say:
1. Navigate to Admin -> Types

**Comment by nickbeau** [comment]
Obsolete
