### ISSUE TITLE
Referencing Task ID not explained in University

### ISSUE THREAD

**Issue by lindabeau70** [World-of-Workflows/WorkflowsUniversity#86]
I didn't realise that when I reference a task ID I need parenthesis - it doesn't seem intuitive like Output.  It seemed more like an ObjectId which doesn't need parenthesis.  Can we explain this in the University under Tasks?
activities.ChooseMonth.TaskId()

**Comment by jimcantor** [comment]
now see https://world-of-workflows.github.io/WorkflowsUniversity/docs/14_javascript_liquid_workflows/javaScriptrainWorldOfWorkflows.html
